//! CLIENT_OWNED over the control plane (D3): a thin tunnel to the same `CoreServerState`,
//! `AuthService`, key directory, SQL authorization and CLIENT_OWNED policy as DMC IPC.
//!
//! Frames are the control plane's length-prefixed JSON, but with an AvroraCore-defined
//! shape (`{"CoreControl": ControlRequest}` / `{"CoreData": DataRequest}`) that can never
//! parse as an `avrora_proto::ControlMsg` (`{"type", "body"}`); the protocol crate in the
//! AvroraClient repository is unchanged.
//!
//! * The TLS connection is the channel (D5): `control:<random>` per accepted connection;
//!   sessions created over it die with it, and an open transaction is rolled back.
//! * Authentication is the D1 contract only (`ClientAuthBegin/Finish` inside the tunnel).
//!   Neither the device mTLS certificate (its private key was generated by the server),
//!   nor the operator's access key / TOTP control session, nor an event-plane runtime
//!   session is accepted as CLIENT_OWNED identity — the dispatcher only knows sessions
//!   issued by `AuthService` on this channel.
//! * Only the shared allowlist (`dmc_server::transport_policy`) is forwarded: no password
//!   authentication, vault, backup, runtime or invite administration through the tunnel.

use std::sync::{Arc, Mutex};

use dmc_protocol::{
    ControlRequest, ControlResponse, DataRequest, DataResponse, RemoteLimits, RequestEnvelope,
    ResponseEnvelope,
};
use dmc_server::transport_policy::{client_owned_preauth_request, client_owned_session_request};
use dmc_server::{CoreServerState, handle_control, handle_data};
use serde::{Deserialize, Serialize};

pub type SharedCore = Arc<Mutex<CoreServerState>>;

pub const CHANNEL_PREFIX: &str = "control:";

// Frames are transient (one per request, dropped right after dispatch); variant size
// does not matter and boxing would only change every call site.
#[allow(clippy::large_enum_variant)]
#[derive(Debug, Serialize, Deserialize)]
pub enum CoreFrame {
    CoreControl(ControlRequest),
    CoreData(DataRequest),
}

#[allow(clippy::large_enum_variant)]
#[derive(Debug, Serialize, Deserialize)]
pub enum CoreFrameReply {
    CoreControlReply(ResponseEnvelope<ControlResponse>),
    CoreDataReply(ResponseEnvelope<DataResponse>),
    /// Fixed, secret-free refusal (not available / not allowed / malformed).
    CoreRefused(String),
}

/// A tunnel frame, or `None` if `body` is something else (a regular `ControlMsg`).
pub fn parse(body: &[u8]) -> Option<CoreFrame> {
    serde_json::from_slice(body).ok()
}

pub fn new_channel() -> String {
    let mut id = [0u8; 16];
    rand::RngCore::fill_bytes(&mut rand::thread_rng(), &mut id);
    format!("{CHANNEL_PREFIX}{}", hex::encode(id))
}

fn lock(core: &SharedCore) -> std::sync::MutexGuard<'_, CoreServerState> {
    core.lock().unwrap_or_else(|p| p.into_inner())
}

pub async fn handle(
    core: Option<SharedCore>,
    channel: String,
    request_id: u64,
    frame: CoreFrame,
) -> CoreFrameReply {
    let Some(core) = core else {
        return CoreFrameReply::CoreRefused(
            "CLIENT_OWNED is not available on this control plane".into(),
        );
    };
    if let CoreFrame::CoreControl(req) = &frame
        && !client_owned_session_request(req)
        && !client_owned_preauth_request(req)
    {
        return CoreFrameReply::CoreRefused("request not available over the control plane".into());
    }
    tokio::task::spawn_blocking(move || {
        let mut s = lock(&core);
        let limits = RemoteLimits::default();
        match frame {
            CoreFrame::CoreControl(body) => {
                match handle_control(
                    &mut s,
                    RequestEnvelope { request_id, body },
                    &limits,
                    &channel,
                ) {
                    Ok(r) => CoreFrameReply::CoreControlReply(r),
                    Err(_) => CoreFrameReply::CoreRefused("malformed request".into()),
                }
            }
            CoreFrame::CoreData(body) => {
                match handle_data(
                    &mut s,
                    RequestEnvelope { request_id, body },
                    &limits,
                    &channel,
                ) {
                    Ok(r) => CoreFrameReply::CoreDataReply(r),
                    Err(_) => CoreFrameReply::CoreRefused("malformed request".into()),
                }
            }
        }
    })
    .await
    .unwrap_or_else(|_| CoreFrameReply::CoreRefused("internal error".into()))
}

/// The TLS connection closed: its sessions end and their open transaction is rolled back.
pub fn close(core: &Option<SharedCore>, channel: &str) {
    if let Some(core) = core {
        let mut s = lock(core);
        s.auth.close_channel(channel);
        s.reap_orphan_transaction();
    }
}
